#!/bin/bash

aws s3 sync . s3://robertboscacci.com --delete \
 --exclude "*/.DS_Store" \
 --exclude ".DS_Store" \
 --exclude ".git*" \
 --exclude "README.md" \
 --acl bucket-owner-full-control --acl public-read
